### ISSUE TITLE
Deployment fails: missing baseFeePerGas

### ISSUE THREAD

**Issue by simon-something** [g-01234/scope#2]
Expect behaviour: deployment of the Counter.sol Foundry template repo contract.

Observed behaviour: Fails with the following error
`ERROR: Deserialization Error: missing field `baseFeePerGas` at line 1 column 39. Response: {"gasUsedRation": [],"oldestBlock":"0x0"}`

Step to reproduce: 
- Update Forge to the latest stable release (`foundryup`)
- Initialise a new Foundry project (`forge init`)
- Install dependencies (`forge install`)
- Run Anvil in a terminal
- Launch VSCode
- Compile the contracts (ETH Scope -> compile)
- Deploy (ETH Scope -> Counter.sol -> Deploy)

System: Foundry v0.2.0, Scope v0.0.2

**Comment by g-01234** [comment]
thank you! should be fixed by latest commit / v0.0.3
